# Configuration for project teamscale-upload, connector code

version = "1.0"

root = true

[server]
url = "https://cqse.teamscale.io/"

[project]
id = "teamscale-upload"

# The value has been set because the repository identifier gets prepended
path = "code"
